#!/bin/bash -ex

set -euo pipefail

# configuration variables with defaults.
color=${color:-auto}
target_host="${target_host:-"openqa.opensuse.org"}"
target_host_proto="${target_host_proto:-"https"}"
dry_run="${dry_run:-"0"}"
tw_openqa_host="${tw_openqa_host:-"https://openqa.opensuse.org"}"
tw_group_id="${tw_group_id:-"1"}"
openqa_cli=${openqa_cli:-retry -e -- openqa-cli}
arch="${arch:-"x86_64"}"
machine="${machine:-"uefi"}"
build_tag=${BUILD_TAG:-}
client_prefix=${client_prefix:-}
flavor=${flavor:-"dev"}
version=${version:-"Tumbleweed"}
full_run=${FULL:-}
full_run_args=${full_run_args:-}
group_id="${group_id:-"openQA"}"
osc=${osc:-retry -e -- osc}
src_project=${src_project:-devel:openQA}
staging_project=${staging_project:-${src_project}:testing}
dst_project=${dst_project:-${src_project}:tested}
submit_target=${submit_target:-openSUSE:Factory}
scenario_definitions="${scenario_definitions:-"scenario-definitions.yaml"}"
XMLSTARLET=$(command -v xmlstarlet || true)
[[ -n $XMLSTARLET ]] || (echo "Need xmlstarlet" >&2 && exit 1)

# shellcheck source=/dev/null
. "$(dirname "$0")"/_common

usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Triggers tests on an openQA instance testing openQA itself.

Can be configured additionally with environment variables.

Options:
 -h, --help         display this help
EOF
    exit "$1"
}

main() {
    opts=$(getopt -o h -l help -n "$0" -- "$@") || usage 1
    eval set -- "$opts"
    while true; do
        case "$1" in
            -h | --help) usage 0 ;;
            --)
                shift
                break
                ;;
            *) break ;;
        esac
    done
    [[ $dry_run == 1 ]] && client_prefix="echo" osc="echo $osc"
    local qcow build rc=0
    download_latest_published_tumbleweed_image

    #  Only use devel:openQA:testing for the hourly runs which we monitor
    # and use for submit requests
    if [[ $full_run ]]; then
        staging_project=$src_project
        flavor="dev-full" # Note: overrides any user-provided flavor
    else
        create_devel_openqa_snapshot || rc=$?
        if [[ $rc != 0 ]]; then
            # clean staging project in case the snapshot creation failed so we don't leave the staging project in an intermediate state
            # note: This is best-effort as it might fail as well if the problem is OBS being down (for long enough so retries didn't help).
            cleanup-obs-project "$staging_project" 'I am sure'
            return "$rc"
        fi
    fi
    trigger
}

download_latest_published_tumbleweed_image() {
    qcow=$(find_latest_published_tumbleweed_image "$tw_group_id" "$arch" "$machine" qcow)
    if [ "$target_host_proto://$target_host" != "$tw_openqa_host" ]; then
        url="${tw_openqa_host}/assets/hdd/${qcow}"

        # instead of manual wget it should also work to provide a whitelisted url to openqa as HDD_1_URL which should then download it itself but a first experiment didn't work
        ${client_prefix} wget -c "$url" -O /var/lib/openqa/factory/hdd/"$qcow"
    fi
    # ensure the build tag conforms to coolo's unwritten rules for the openQA dashboard
    build=$(echo "$build_tag" | sed -e "s/jenkins-trigger-openQA_in_openQA-/:/" -e "s/-/./g")
}

create_snapshots() {
    local package=$1
    log-info "Creating snapshots of $package"
    $osc release --no-delay --target-project "$staging_project" --target-repository=openSUSE_Tumbleweed -r openSUSE_Tumbleweed -a x86_64 "$src_project" "$package"
}

# To avoid having a big changelog header (with date, email, blank line, version
# and then the actual commit message) for every commit (or every push / service
# trigger) we manipulate the .changes file and _servicedata, setting it back
# to the devel:openQA:tested version and then let OBS generate it again with
# all commits since that version in one changelog entry. With this we get
# one update header per hour as a maximum.
sync_changesrevision() {
    log-info "sync_changesrevision $*"
    local dir=$1
    local package=$2
    local target_rev=$3
    path="$dir/$package"
    $client_prefix "$XMLSTARLET" ed -L -u "//param[@name='changesrevision']" -v "$target_rev" "$path"/_servicedata
    if ! diff -u "$path"/.osc/sources/_servicedata "$path"/_servicedata; then
        debug_osc up "$path"
        debug_osc cat "$dst_project" "$package" "$package".changes > "$path/$package".changes
        debug_osc ci -m "sync changesrevision with $dst_project" "$path"
        debug_osc up --server-side-source-service-files "$path"
    fi
}

create_devel_openqa_snapshot() {
    local auto_submit_packages staged_packages target_rev dst_rev
    auto_submit_packages=$(list_packages "$dst_project")
    staged_packages=$(list_packages "$staging_project") || true # osc ls returns non-zero return code for empty projects
    if [[ $staged_packages ]]; then
        echo "+++ NOTE+++ Only triggering tests from $src_project (not overriding $staging_project and doing a submission) because $staging_project still contains packages. You might need to do a manual cleanup if no other pipeline is running. Packages: $staged_packages" \
            | tee job_post_skip_submission
        staging_project=$src_project
        return
    elif [[ -e job_post_skip_submission ]]; then
        rm job_post_skip_submission
    fi
    log-info "Checking if all relevant packages are built and published before creating snapshot under $staging_project"
    for package in $auto_submit_packages; do
        local state
        state=$($osc results -r openSUSE_Tumbleweed -a x86_64 --no-multibuild "$src_project" "$package")
        if grep -q -v 'succeeded\|disabled' <<< "$state"; then
            echo -e "Package $package is not yet ready for release\n$state" | tee job_post_skip_submission
            delete_packages_from_obs_project "$staging_project"
            return
        fi
        target_rev=$(last_revision "$submit_target" "$package")
        dst_rev=$(last_revision "$dst_project" "$package")
        log-info "Last revision for '$submit_target/$package': $target_rev"
        log-info "Last revision for '$dst_project/$package': $dst_rev"
        debug_osc co --server-side-source-service-files "$src_project"/"$package"
        sync_changesrevision "$src_project" "$package" "$dst_rev"
        create_snapshots "$package"
    done
    log-info "Wait until all packages are published under $staging_project"
    $osc prjresults --watch --xml -r openSUSE_Tumbleweed -a x86_64 "$staging_project"
}

trigger() {
    # prevent host access problem when running within o3 infrastructure
    # where o3 is not reachable over https
    declare -a ARGS
    [[ $target_host = "openqa.opensuse.org" ]] && ARGS+=("OPENQA_HOST=http://openqa.opensuse.org")
    # shellcheck disable=SC2206
    [[ $full_run_args ]] && ARGS+=($full_run_args)

    local schedule_args=()
    if [[ $scenario_definitions =~ ^https?:// ]]; then
        schedule_args+=("SCENARIO_DEFINITIONS_YAML_FILE=$scenario_definitions" "async=1")
    elif [[ -f $scenario_definitions ]]; then
        schedule_args+=("--param-file" "SCENARIO_DEFINITIONS_YAML=$scenario_definitions")
    else
        local scenario_url="https://raw.githubusercontent.com/os-autoinst/os-autoinst-distri-openQA/master/${scenario_definitions}"
        schedule_args+=("SCENARIO_DEFINITIONS_YAML_FILE=$scenario_url" "async=1")
    fi

    # shellcheck disable=SC2086
    ${client_prefix} ${openqa_cli} \
        schedule --host "${target_host_proto}://${target_host}" \
        "${schedule_args[@]}" \
        VERSION="${version}" \
        DISTRI=openqa FLAVOR="${flavor}" ARCH="${arch}" \
        HDD_1="$qcow" BUILD="${build}" _GROUP="${group_id}" \
        OPENQA_OBS_PROJECT="$staging_project" \
        "${ARGS[@]}" \
        | tee full_job_post_response
    head -1 full_job_post_response > job_post_response
    rm -f full_job_post_response
}

caller 0 > /dev/null || main "$@"
