---
name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - run: |
#          pip install --upgrade pip
#          pip install pytest mocker pytest-mock
#          python --version
#          pytest --version
#      - run: |
#          sudo apt-get install cpanminus
#          sudo cpanm -n -M https://cpan.metacpan.org --installdeps .
      - name: unit- and integration tests
        run: |
         make test-unit

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Static checks
        run: |
         sudo apt-get install yamllint shellcheck shfmt
         make checkstyle
